### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by sergeycherepanov** [vvampirius/retracker#1]
```
root@retracker:~# go install 'github.com/vvampirius/retracker@latest'
# github.com/vvampirius/retracker
go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20240416120713-0b932dd2ecb3/receiverAnnounce.go:149:13: forward.Host undefined (type "github.com/vvampirius/retracker/common".Forward has no field or method Host)
go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20240416120713-0b932dd2ecb3/receiverAnnounce.go:150:23: forward.Host undefined (type "github.com/vvampirius/retracker/common".Forward has no field or method Host)
```

**Comment by vvampirius** [comment]
Try again please. It seems fixed.


`% go install 'github.com/vvampirius/retracker@latest'
go: downloading github.com/vvampirius/retracker v0.0.0-20241108170741-19ca869ddff5
go: downloading github.com/prometheus/client_golang v1.20.5
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/vvampirius/retracker/bittorrent/tracker v0.0.0-20241018131108-6661250eb98b
go: downloading github.com/vvampirius/retracker/common v0.0.0-20241018131108-6661250eb98b
go: downloading github.com/vvampirius/retracker/bittorrent/common v0.0.0-20241018131108-6661250eb98b
go: downloading github.com/vvampirius/retracker/bittorrent/response v0.0.0-20241018131108-6661250eb98b
go: downloading github.com/zeebo/bencode v1.0.0
go: downloading github.com/prometheus/common v0.60.1
go: downloading github.com/klauspost/compress v1.17.11
go: downloading github.com/prometheus/client_model v0.6.1
go: downloading google.golang.org/protobuf v1.35.1
go: downloading github.com/cespare/xxhash/v2 v2.3.0
go: downloading github.com/prometheus/procfs v0.15.1
go: downloading github.com/beorn7/perks v1.0.1
go: downloading github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822
go: downloading golang.org/x/sys v0.27.0`
