### ISSUE TITLE
Fatal error: concurrent map read and map write

### ISSUE THREAD

**Issue by Spinaker70** [vvampirius/retracker#2]
ноя 08 14:21:35 neftjan retracker[17463]: fatal error: concurrent map read and map write
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 13 [running]:
ноя 08 14:21:35 neftjan retracker[17463]: main.(*Storage).Update(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/storage.go:15
ноя 08 14:21:35 neftjan retracker[17463]: main.(*ReceiverAnnounce).ProcessAnnounce(0xc00009aee0, {0xc0001821e0?, 0xc0000b08d8?}, {0xc0001aa420?, 0xc0001aff80?}, {0xc0001aa468?, 0x6c0982?}, {
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/receiverAnnounce.go:92 +0x1d3
ноя 08 14:21:35 neftjan retracker[17463]: main.(*ReceiverAnnounce).httpHandler(0xc00009aee0, {0x98db40, 0xc0001ae1c0}, 0xc0001903c0)
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/receiverAnnounce.go:37 +0x7d5
ноя 08 14:21:35 neftjan retracker[17463]: net/http.HandlerFunc.ServeHTTP(0xc6cdc0?, {0x98db40?, 0xc0001ae1c0?}, 0x6b8856?)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2220 +0x29
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*ServeMux).ServeHTTP(0x466ff9?, {0x98db40, 0xc0001ae1c0}, 0xc0001903c0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2747 +0x1ca
ноя 08 14:21:35 neftjan retracker[17463]: net/http.serverHandler.ServeHTTP({0xc00019e900?}, {0x98db40?, 0xc0001ae1c0?}, 0x6?)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3210 +0x8e
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*conn).serve(0xc000216e10, {0x98e480, 0xc000144900})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2092 +0x5d0
ноя 08 14:21:35 neftjan retracker[17463]: created by net/http.(*Server).Serve in goroutine 1
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3360 +0x485
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 1 [runnable]:
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.runtime_pollWait(0x7f1b8a359e28, 0x72)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/runtime/netpoll.go:351 +0x85
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*pollDesc).wait(0xc000111200?, 0x900000036?, 0x0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_poll_runtime.go:84 +0x27
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*pollDesc).waitRead(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_poll_runtime.go:89
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*FD).Accept(0xc000111200)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_unix.go:620 +0x295
ноя 08 14:21:35 neftjan retracker[17463]: net.(*netFD).accept(0xc000111200)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/fd_unix.go:172 +0x29
ноя 08 14:21:35 neftjan retracker[17463]: net.(*TCPListener).accept(0xc0000d10c0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/tcpsock_posix.go:159 +0x1e
ноя 08 14:21:35 neftjan retracker[17463]: net.(*TCPListener).Accept(0xc0000d10c0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/tcpsock.go:372 +0x30
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*Server).Serve(0xc0001462d0, {0x98dc60, 0xc0000d10c0})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3330 +0x30c
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*Server).ListenAndServe(0xc0001462d0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3259 +0x71
ноя 08 14:21:35 neftjan retracker[17463]: net/http.ListenAndServe(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3514
ноя 08 14:21:35 neftjan retracker[17463]: main.main()
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/main.go:75 +0x595
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 23 [sleep]:
ноя 08 14:21:35 neftjan retracker[17463]: time.Sleep(0x34630b8a000)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/runtime/time.go:315 +0xf2
ноя 08 14:21:35 neftjan retracker[17463]: main.(*TempStorage).cleanRoutine(0xc000098aa0)
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/tempStorage.go:38 +0x13b
ноя 08 14:21:35 neftjan retracker[17463]: created by main.NewTempStorage in goroutine 1
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/tempStorage.go:70 +0x16c
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 24 [sleep]:
ноя 08 14:21:35 neftjan retracker[17463]: time.Sleep(0xdf8475800)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/runtime/time.go:315 +0xf2
ноя 08 14:21:35 neftjan retracker[17463]: main.(*Storage).purgeRoutine(0xc000098ac0)
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/storage.go:38 +0x34
ноя 08 14:21:35 neftjan retracker[17463]: created by main.NewStorage in goroutine 1
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/storage.go:69 +0xac
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 88 [runnable]:
ноя 08 14:21:35 neftjan retracker[17463]: net/url.unescape({0xc0003245f5, 0x24}, 0x6)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/url/url.go:201 +0x8a7
ноя 08 14:21:35 neftjan retracker[17463]: net/url.QueryUnescape(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/url/url.go:185
ноя 08 14:21:35 neftjan retracker[17463]: net/url.parseQuery(0xc000372ed0, {0xc0003245ae?, 0xc8?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/url/url.go:988 +0x13b
ноя 08 14:21:35 neftjan retracker[17463]: net/url.ParseQuery(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/url/url.go:965
ноя 08 14:21:35 neftjan retracker[17463]: net/url.(*URL).Query(0xc00032462e?)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/url/url.go:1159 +0x39
ноя 08 14:21:35 neftjan retracker[17463]: main.(*ReceiverAnnounce).httpHandler(0xc00009aee0, {0x98db40, 0xc00032ca80}, 0xc000322f00)
ноя 08 14:21:35 neftjan retracker[17463]:         /home/spinaker/go/pkg/mod/github.com/vvampirius/retracker@v0.0.0-20241018131108-6661250eb98b/receiverAnnounce.go:50 +0x7f1
ноя 08 14:21:35 neftjan retracker[17463]: net/http.HandlerFunc.ServeHTTP(0xc6cdc0?, {0x98db40?, 0xc00032ca80?}, 0x6b8856?)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2220 +0x29
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*ServeMux).ServeHTTP(0x466ff9?, {0x98db40, 0xc00032ca80}, 0xc000322f00)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2747 +0x1ca
ноя 08 14:21:35 neftjan retracker[17463]: net/http.serverHandler.ServeHTTP({0xc000372c00?}, {0x98db40?, 0xc00032ca80?}, 0x6?)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3210 +0x8e
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*conn).serve(0xc000380090, {0x98e480, 0xc000144900})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:2092 +0x5d0
ноя 08 14:21:35 neftjan retracker[17463]: created by net/http.(*Server).Serve in goroutine 1
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:3360 +0x485
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 89 [IO wait]:
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.runtime_pollWait(0x7f1b8a359d20, 0x72)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/runtime/netpoll.go:351 +0x85
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*pollDesc).wait(0xc000302c00?, 0xc000372c11?, 0x0)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_poll_runtime.go:84 +0x27
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*pollDesc).waitRead(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_poll_runtime.go:89
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*FD).Read(0xc000302c00, {0xc000372c11, 0x1, 0x1})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_unix.go:165 +0x27a
ноя 08 14:21:35 neftjan retracker[17463]: net.(*netFD).Read(0xc000302c00, {0xc000372c11?, 0xc00004bf48?, 0x46e7b0?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/fd_posix.go:55 +0x25
ноя 08 14:21:35 neftjan retracker[17463]: net.(*conn).Read(0xc000306058, {0xc000372c11?, 0x0?, 0xc8ee40?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/net.go:189 +0x45
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*connReader).backgroundRead(0xc000372c00)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:690 +0x37
ноя 08 14:21:35 neftjan retracker[17463]: created by net/http.(*connReader).startBackgroundRead in goroutine 88
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:686 +0xb6
ноя 08 14:21:35 neftjan retracker[17463]: goroutine 72 [runnable]:
ноя 08 14:21:35 neftjan retracker[17463]: syscall.Syscall(0x0, 0x7, 0xc00019e911, 0x1)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/syscall/syscall_linux.go:73 +0x25
ноя 08 14:21:35 neftjan retracker[17463]: syscall.read(0xc000214500?, {0xc00019e911?, 0x467f00?, 0x0?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/syscall/zsyscall_linux_amd64.go:736 +0x38
ноя 08 14:21:35 neftjan retracker[17463]: syscall.Read(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/syscall/syscall_unix.go:183
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.ignoringEINTRIO(...)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_unix.go:745
ноя 08 14:21:35 neftjan retracker[17463]: internal/poll.(*FD).Read(0xc000214500, {0xc00019e911, 0x1, 0x1})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/internal/poll/fd_unix.go:161 +0x2ae
ноя 08 14:21:35 neftjan retracker[17463]: net.(*netFD).Read(0xc000214500, {0xc00019e911?, 0xc000312748?, 0x46e7b0?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/fd_posix.go:55 +0x25
ноя 08 14:21:35 neftjan retracker[17463]: net.(*conn).Read(0xc000050030, {0xc00019e911?, 0x0?, 0xc8ee40?})
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/net.go:189 +0x45
ноя 08 14:21:35 neftjan retracker[17463]: net/http.(*connReader).backgroundRead(0xc00019e900)
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:690 +0x37
ноя 08 14:21:35 neftjan retracker[17463]: created by net/http.(*connReader).startBackgroundRead in goroutine 13
ноя 08 14:21:35 neftjan retracker[17463]:         /snap/go/10730/src/net/http/server.go:686 +0xb6

**Comment by Spinaker70** [comment]
● retracker.service - Retracker daemon
   Loaded: loaded (/etc/systemd/system/retracker.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2024-11-08 14:54:56 +07; 6s ago
 Main PID: 18561 (retracker)
    Tasks: 7 (limit: 4315)
   CGroup: /system.slice/retracker.service
           └─18561 /opt/retracker/retracker -l :8080 -x -p

**Comment by vvampirius** [comment]
added Mutex to Storage
