### ISSUE TITLE
Поле "пиры" неверной длины

### ISSUE THREAD

**Issue by Spinaker70** [vvampirius/retracker#4]
![image](https://github.com/user-attachments/assets/24ab0b85-cfad-41c6-8407-f3363cc1359f)

**Comment by Spinaker70** [comment]
uTorrent 1.8.2

**Comment by vvampirius** [comment]
Со стороны ретрэкера при этом в логах ничего нет подозрительного?

**Comment by Spinaker70** [comment]
retracker[12649]: debug#receiverAnnounce.go:30: GET 127.0.0.1:54126 2a04:3800:0:f80:e1c1:6d57:5665:81d7 '/announce?info_hash=%24m%f8%e71%27%27u%01~%8b%cd%3a%96%12k%e5_%b0%91&peer_id=-UT1820-%fd%3b%17%fc%ff%2fN%8d%9c%db%ed%ab&port=25876&u
retracker[12649]: debug#receiverAnnounce.go:53: Peers count: 1
retracker[12649]: IPv6 peer in compacted mode: 2a04:3800:0:f80:e1c1:6d57:5665:81d7:25876

**Comment by vvampirius** [comment]
Исправил одну ошибку. Возможно с этим связано. У меня проблема не воспроизвелась.
Прошу проверить. Если не помогло, то прошу приложить лог как выше, только не обрезанный.

**Comment by vvampirius** [comment]
исправил
