### ISSUE TITLE
Not found 404 при методе SCRAPE

### ISSUE THREAD

**Issue by maxbur89** [vvampirius/retracker#5]
Добрый день!

Заметил, что retracker 0.9.3 на запрос по методу /scrape выдает NOT FOUND 404.
Пример запроса и скрин ниже. Это ошибка или данное действие не обязательно (https://github.com/ablaternae/torrent-manual/blob/trunk/index.md)? Торрент с трекеров rutracker.org и rutor.is. Клиент Transmission (Linux).

http://retracker.local/scrape?info_hash=%fd%ce%d7%28%da%d8G%be%b2%1e%e8nBN%28P%90%ec%60%85
![Снимок экрана от 2024-12-07 00-11-00](https://github.com/user-attachments/assets/c0f6b497-1864-4aa5-9655-35ec58a277b5)

**Comment by maxbur89** [comment]
Скорее всего SCRAPE выполняется при запросе дополнительных участников. Запрос количества участников выполняется без ошибки. Добавляю скрин с ошибкой при scrape запросе.
![Снимок экрана от 2024-12-08 01-03-31](https://github.com/user-attachments/assets/3c35d358-f45d-4282-b136-fef0e8d496d2)

**Comment by vvampirius** [comment]
Добрый день.

/scrape - это просто дополнительная статистика по торренту (сколько сидеров, личеров, скачано раз). Особого смысла в ней нет.
![Screenshot 2024-12-09 at 00 21 13](https://github.com/user-attachments/assets/cd1cfb89-f7fc-4f84-a087-f53e291a11d7)
Но эндпоинт добавил.
