### ISSUE TITLE
Dashboard для Grafana

### ISSUE THREAD

**Issue by maxbur89** [vvampirius/retracker#6]
Добрый день!

Подскажите, пожалуйста, есть ли у вас Grafana dashboard для retracker?
Было бы отлично, если сможете добавить его в этот github репозиторий или выложите в общедоступные на сайте Grafana.
Заранее спасибо.

**Comment by vvampirius** [comment]
Добрый день.

Нет, дашборда мысли делать не было. В ретрекере всего две метрики на текущий момент (requests и forwarder_status). Ради них можно дашборд выкладывать смысла не вижу. Нет сложности самостоятельно вручную следать под себя.

**Comment by vvampirius** [comment]
Добрый день.

Нет, дашборда мысли делать не было. В ретрекере всего две метрики на текущий момент (requests и forwarder_status). Ради них можно дашборд выкладывать смысла не вижу. Нет сложности самостоятельно вручную следать под себя.
