### ISSUE TITLE
Ошибка при запросе favicon.ico

### ISSUE THREAD

**Issue by maxbur89** [vvampirius/retracker#7]
Добрый день!

Заметил, что клиент Transmission (Linux) запрашивает favicon.ico. При этом retracker 0.9.3 выдает ошибку Not Found 404.
По какой-то причине torrent-клиент при этом не ищет локальных пиров...
Решил проблему добавление location в nginx, но в руководстве retracker написано, что можно использовать без nginx и если такая проблема не только у меня, не могли бы исправить данное поведение (чтобы retracker мог отвечать на такой запрос)?
Скрин с WireShark:
![Снимок экрана от 2024-12-07 00-21-27](https://github.com/user-attachments/assets/fcb0b234-1d58-4ae9-8047-0ed8279e2b94)

**Comment by vvampirius** [comment]
добавил /favicon.ico
